# Generated by Django 3.1.7 on 2021-05-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneda',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tipopago',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
