# Generated by Django 3.2.4 on 2021-07-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_auto_20210717_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eliminacionpagos',
            old_name='eliminadoPor',
            new_name='procesadoPor',
        ),
        migrations.AddField(
            model_name='eliminacionpagos',
            name='respuesta',
            field=models.IntegerField(default=None),
        ),
    ]
