# Generated by Django 3.2.4 on 2021-07-18 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pagos', '0004_auto_20210717_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eliminacionpagos',
            name='procesadoPor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
