# Generated by Django 3.2.4 on 2021-07-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_alter_eliminacionpagos_procesadopor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eliminacionpagos',
            name='respuesta',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
