# Generated by Django 3.2.4 on 2021-07-18 02:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0006_alter_eliminacionpagos_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='eliminacionpagos',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
