# Generated by Django 3.1.7 on 2021-08-28 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_auto_20210827_2222'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pagos', '0010_pago_forma_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='tipo_pago',
        ),
        migrations.CreateModel(
            name='cobrosExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('fecha_limite', models.DateField()),
                ('codigo_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cobro', models.DateField()),
                ('monto', models.FloatField()),
                ('tipo_moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.moneda')),
                ('tipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.tipopago')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pago',
            name='cobro',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pagos.cobro'),
            preserve_default=False,
        ),
    ]
