# Generated by Django 3.1.7 on 2021-10-29 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_auto_20210828_1121'),
        ('pagos', '0016_alter_tipogasto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='codigo_curso',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usuarios.curso'),
        ),
    ]
