# Generated by Django 3.1.7 on 2021-11-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0017_cobro_codigo_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='fecha_gasto',
            field=models.DateField(),
        ),
    ]
