# Generated by Django 3.1.7 on 2021-05-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_userextra_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteoAnualEstudiantes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='userextra',
            name='curso_a_estudiar',
        ),
    ]
