# Generated by Django 3.1.7 on 2021-05-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20210522_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nivelacademico',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='sexo',
            name='nombre',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='direccion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='dpi',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
