# Generated by Django 3.1.7 on 2021-05-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20210522_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivelacademico',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rol',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sexo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
