# Generated by Django 3.1.7 on 2021-05-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20210522_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextra',
            name='fecha_nacimiento',
            field=models.DateField(blank=True),
        ),
    ]
