# Generated by Django 3.1.7 on 2021-05-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20210523_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextra',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
