# Generated by Django 3.1.7 on 2021-07-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20210524_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='cuota',
            field=models.FloatField(default=1000.0),
        ),
        migrations.AddField(
            model_name='curso',
            name='duracion',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='curso',
            name='inscripcion',
            field=models.FloatField(default=500.0),
        ),
        migrations.AddField(
            model_name='curso',
            name='otros',
            field=models.FloatField(default=0.0),
        ),
    ]
