# Generated by Django 3.1.7 on 2021-08-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_auto_20210702_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='otros',
        ),
        migrations.AddConstraint(
            model_name='llevacurso',
            constraint=models.UniqueConstraint(fields=('user', 'curso'), name='llevar el curso una vez'),
        ),
    ]
