# Generated by Django 3.1.7 on 2021-08-28 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_auto_20210827_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='cuota',
            new_name='cuota_quetzales',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='inscripcion',
            new_name='inscripcion_quetzales',
        ),
        migrations.AddField(
            model_name='curso',
            name='cuota_dolares',
            field=models.FloatField(default=1000.0),
        ),
        migrations.AddField(
            model_name='curso',
            name='inscripcion_dolares',
            field=models.FloatField(default=500.0),
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.moneda')),
            ],
        ),
        migrations.AddField(
            model_name='userextra',
            name='nacionalidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.nacionalidad'),
            preserve_default=False,
        ),
    ]
