# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRegisterexpenses():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_registerexpenses(self):
    # Test name: register_expenses
    # Step # | name | target | value
    # 1 | open | /pagos/control/ | 
    self.driver.get("https://plus-academy.herokuapp.com/pagos/control/")
    # 2 | setWindowSize | 1247x700 | 
    self.driver.set_window_size(1247, 700)
    # 3 | click | linkText=Ingreso Gasto | 
    self.driver.find_element(By.LINK_TEXT, "Ingreso Gasto").click()
    # 4 | click | id=id_tipo_gasto | 
    self.driver.find_element(By.ID, "id_tipo_gasto").click()
    # 5 | select | id=id_tipo_gasto | label=Luz
    dropdown = self.driver.find_element(By.ID, "id_tipo_gasto")
    dropdown.find_element(By.XPATH, "//option[. = 'Luz']").click()
    # 6 | click | css=option:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(2)").click()
    # 7 | click | id=id_cantidad | 
    self.driver.find_element(By.ID, "id_cantidad").click()
    # 8 | type | id=id_cantidad | 700
    self.driver.find_element(By.ID, "id_cantidad").send_keys("700")
    # 9 | click | css=.btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    # 10 | click | linkText=Caja Chica | 
    self.driver.find_element(By.LINK_TEXT, "Caja Chica").click()
    # 11 | click | css=.dataTables_scrollHeadInner .sorting:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".dataTables_scrollHeadInner .sorting:nth-child(1)").click()
    # 12 | click | css=.sorting_asc:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".sorting_asc:nth-child(1)").click()
    # 13 | click | css=.sorting_desc | 
    self.driver.find_element(By.CSS_SELECTOR, ".sorting_desc").click()
    # 14 | click | css=.sorting_asc | 
    self.driver.find_element(By.CSS_SELECTOR, ".sorting_asc").click()
    # 15 | click | css=.dataTables_scrollHeadInner .sorting:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".dataTables_scrollHeadInner .sorting:nth-child(2)").click()
    # 16 | click | css=.sorting_asc | 
    self.driver.find_element(By.CSS_SELECTOR, ".sorting_asc").click()
  
