# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDeleteregister():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_deleteregister(self):
    # Test name: delete_register
    # Step # | name | target | value
    # 1 | open | /pagos/control/ | 
    self.driver.get("https://plus-academy.herokuapp.com/pagos/control/")
    # 2 | setWindowSize | 1247x700 | 
    self.driver.set_window_size(1247, 700)
    # 3 | click | linkText=Control de Pagos | 
    self.driver.find_element(By.LINK_TEXT, "Control de Pagos").click()
    # 4 | click | css=#\31 1 .btn-solicitar-eliminacion | 
    self.driver.find_element(By.CSS_SELECTOR, "#\\31 1 .btn-solicitar-eliminacion").click()
    # 5 | mouseOver | css=#\31 1 .btn-solicitar-eliminacion | 
    element = self.driver.find_element(By.CSS_SELECTOR, "#\\31 1 .btn-solicitar-eliminacion")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 6 | mouseOut | css=#\31 1 .btn-solicitar-eliminacion | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 7 | click | id=btn-solicitar-eliminacion | 
    self.driver.find_element(By.ID, "btn-solicitar-eliminacion").click()
    # 8 | click | css=.btn-success | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
    # 9 | click | linkText=Pagos Solicitados a Eliminar | 
    self.driver.find_element(By.LINK_TEXT, "Pagos Solicitados a Eliminar").click()
    # 10 | click | id=btn2 | 
    self.driver.find_element(By.ID, "btn2").click()
    # 11 | click | css=#modalConfirmation .btn | 
    self.driver.find_element(By.CSS_SELECTOR, "#modalConfirmation .btn").click()
    # 12 | click | linkText=Pagos Eliminados | 
    self.driver.find_element(By.LINK_TEXT, "Pagos Eliminados").click()
  
