# Generated by Selenium IDE
# Invalid user test

################################
# BDD tests                    #
# Related to login.feature     #
################################

#################################
# Scenario: Ingresar a la pagina
#################################

import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestInvalidlogin():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_invalidlogin(self):
    # Test name: invalid_login
    # Step # | name | target | value
    # 1 | open | /usuarios/login/ | 
    self.driver.get("https://plus-academy.herokuapp.com/usuarios/login/")
    # 2 | setWindowSize | 1382x744 | 
    self.driver.set_window_size(1382, 744)
    # 3 | click | id=id_username | 
    
    ##########################
    #Given: Un usuario anónimo
    ##########################

    self.driver.find_element(By.ID, "id_username").click()
    # 4 | type | id=id_username | adminAcademy
    self.driver.find_element(By.ID, "id_username").send_keys("adminAcademy")
    # 5 | click | id=id_password | 
    self.driver.find_element(By.ID, "id_password").click()
    # 6 | click | id=id_password | 
    self.driver.find_element(By.ID, "id_password").click()
    # 7 | type | id=id_password | 12345
    self.driver.find_element(By.ID, "id_password").send_keys("12345")
    # 8 | click | css=.btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    # 9 | click | id=id_password | 
    self.driver.find_element(By.ID, "id_password").click()
    # 10 | type | id=id_password | admin12345
    self.driver.find_element(By.ID, "id_password").send_keys("admin12345")
    # 11 | sendKeys | id=id_password | ${KEY_ENTER}
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    # 12 | click | id=id_password | 
    self.driver.find_element(By.ID, "id_password").click()
    # 13 | type | id=id_password | admin123
    self.driver.find_element(By.ID, "id_password").send_keys("admin123")
    # 14 | sendKeys | id=id_password | ${KEY_ENTER}
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    # 15 | click | id=id_username | 
    self.driver.find_element(By.ID, "id_username").click()
    # 16 | click | id=id_username | 
    self.driver.find_element(By.ID, "id_username").click()
    # 17 | doubleClick | id=id_username | 
    element = self.driver.find_element(By.ID, "id_username")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 18 | click | id=id_username | 
    self.driver.find_element(By.ID, "id_username").click()
    # 19 | type | id=id_username | jenni
    self.driver.find_element(By.ID, "id_username").send_keys("jenni")
    # 20 | click | id=id_password | 
    self.driver.find_element(By.ID, "id_password").click()
    # 21 | type | id=id_password | jeni
    self.driver.find_element(By.ID, "id_password").send_keys("jeni")
    # 22 | sendKeys | id=id_password | ${KEY_ENTER}
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    # 23 | click | id=id_username | 
    self.driver.find_element(By.ID, "id_username").click()
    # 24 | click | id=id_username | 
    self.driver.find_element(By.ID, "id_username").click()
    # 25 | doubleClick | id=id_username | 
    element = self.driver.find_element(By.ID, "id_username")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()

    #################################################
    #When: Envio datos inválidos a la página de login
    #################################################

    # 26 | type | id=id_username | adminAcademy
    self.driver.find_element(By.ID, "id_username").send_keys("adminAcademy")
    # 27 | click | id=id_password | 
    self.driver.find_element(By.ID, "id_password").click()
    # 28 | type | id=id_password | plu?1234
    self.driver.find_element(By.ID, "id_password").send_keys("plu?1234")
    # 29 | sendKeys | id=id_password | ${KEY_ENTER}
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    # 30 | click | id=id_password | 
    self.driver.find_element(By.ID, "id_password").click()

    ##########################################################
    #Then: Soy redireccionado a una pantalla de fallo de login
    ##########################################################

    # 31 | type | id=id_password | plus?1234
    self.driver.find_element(By.ID, "id_password").send_keys("plus?1234")
    # 32 | sendKeys | id=id_password | ${KEY_ENTER}
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    # 33 | click | css=html | 
    self.driver.find_element(By.CSS_SELECTOR, "html").click()
  
