# Generated by Selenium IDE
# Test of request to delete a record

################################
# BDD tests                    #
# Related to pagos.feature     #
################################

#################################################################################
# Scenario: Se desea eliminar la informacion de un pago debido a una equivocación
#################################################################################

import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDeleteregisterrequest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_deleteregisterrequest(self):
    # Test name: delete_register_request
    # Step # | name | target | value

    #############################################
    # Given: La página de visualización de pagos
    #############################################
    
    # 1 | open | /pagos/control/ | 
    self.driver.get("https://plus-academy.herokuapp.com/pagos/control/")
    # 2 | setWindowSize | 1258x718 | 
    self.driver.set_window_size(1258, 718)
    
    ####################################################################################################
    # When: El usuario que administra los pagos se equivocó al ingresar un pago al estudiante equivocado.
    #####################################################################################################


    
    

    # 3 | click | xpath=//tr[@id='6']/td[7]/button | 
    self.driver.find_element(By.XPATH, "//tr[@id=\'6\']/td[7]/button").click()


    ##############################################################################################
    # Then: Se da la opción de modificar los campos. En otra instancia se puede eliminar el pago
    ##############################################################################################
    # 4 | click | id=btn-solicitar-eliminacion | 
    self.driver.find_element(By.ID, "btn-solicitar-eliminacion").click()

    ##############################################################################################
    # And: Se modifica el registro y se visualiza con los nuevos valores en la tabla
    ##############################################################################################
    # 5 | click | css=.btn > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn > span").click()
  
