# Generated by Selenium IDE

################################
# BDD tests                    #
# Related to .feature     #
################################


import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestNewuser():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_newuser(self):
    # Test name: new_user
    # Step # | name | target | value
    # 1 | open | /pagos/control/ | 
    self.driver.get("https://plus-academy.herokuapp.com/pagos/control/")
    # 2 | setWindowSize | 1247x700 | 
    self.driver.set_window_size(1247, 700)
    # 3 | click | linkText=Ingreso Usuario | 
    self.driver.find_element(By.LINK_TEXT, "Ingreso Usuario").click()
    # 4 | click | id=id_username | 
    self.driver.find_element(By.ID, "id_username").click()
    # 5 | type | id=id_username | jenni
    self.driver.find_element(By.ID, "id_username").send_keys("jenni")
    # 6 | click | css=.input-form | 
    self.driver.find_element(By.CSS_SELECTOR, ".input-form").click()
    # 7 | click | id=id_first_name | 
    self.driver.find_element(By.ID, "id_first_name").click()
    # 8 | type | id=id_first_name | j
    self.driver.find_element(By.ID, "id_first_name").send_keys("j")
    # 9 | sendKeys | id=id_first_name | ${KEY_DOWN}
    self.driver.find_element(By.ID, "id_first_name").send_keys(Keys.DOWN)
    # 10 | sendKeys | id=id_first_name | ${KEY_TAB}
    self.driver.find_element(By.ID, "id_first_name").send_keys(Keys.TAB)
    # 11 | type | id=id_last_name | Sa
    self.driver.find_element(By.ID, "id_last_name").send_keys("Sa")
    # 12 | sendKeys | id=id_last_name | ${KEY_DOWN}
    self.driver.find_element(By.ID, "id_last_name").send_keys(Keys.DOWN)
    # 13 | sendKeys | id=id_last_name | ${KEY_TAB}
    self.driver.find_element(By.ID, "id_last_name").send_keys(Keys.TAB)
    # 14 | click | id=id_email | 
    self.driver.find_element(By.ID, "id_email").click()
    # 15 | type | id=id_email | san@plusacademy.edu.gt
    self.driver.find_element(By.ID, "id_email").send_keys("san@plusacademy.edu.gt")
    # 16 | click | id=id_dpi | 
    self.driver.find_element(By.ID, "id_dpi").click()
    # 17 | type | id=id_dpi | 12391039210
    self.driver.find_element(By.ID, "id_dpi").send_keys("12391039210")
    # 18 | click | id=id_telefono | 
    self.driver.find_element(By.ID, "id_telefono").click()
    # 19 | type | id=id_telefono | 45564515
    self.driver.find_element(By.ID, "id_telefono").send_keys("45564515")
    # 20 | click | id=id_direccion | 
    self.driver.find_element(By.ID, "id_direccion").click()
    # 21 | type | id=id_direccion | Zona 
    self.driver.find_element(By.ID, "id_direccion").send_keys("Zona ")
    # 22 | sendKeys | id=id_direccion | ${KEY_DOWN}
    self.driver.find_element(By.ID, "id_direccion").send_keys(Keys.DOWN)
    # 23 | type | id=id_direccion | Zona 
    self.driver.find_element(By.ID, "id_direccion").send_keys("Zona ")
    # 24 | sendKeys | id=id_direccion | ${KEY_DOWN}
    self.driver.find_element(By.ID, "id_direccion").send_keys(Keys.DOWN)
    # 25 | sendKeys | id=id_direccion | ${KEY_TAB}
    self.driver.find_element(By.ID, "id_direccion").send_keys(Keys.TAB)
    # 26 | click | id=id_direccion | 
    self.driver.find_element(By.ID, "id_direccion").click()
    # 27 | click | id=id_fecha_nacimiento | 
    self.driver.find_element(By.ID, "id_fecha_nacimiento").click()
    # 28 | type | id=id_fecha_nacimiento | 2/4/2000
    self.driver.find_element(By.ID, "id_fecha_nacimiento").send_keys("2/4/2000")
    # 29 | select | id=id_sexo | label=Femenino
    dropdown = self.driver.find_element(By.ID, "id_sexo")
    dropdown.find_element(By.XPATH, "//option[. = 'Femenino']").click()
    # 30 | click | css=#id_sexo > option:nth-child(3) | 
    self.driver.find_element(By.CSS_SELECTOR, "#id_sexo > option:nth-child(3)").click()
    # 31 | click | id=id_nivel_academico | 
    self.driver.find_element(By.ID, "id_nivel_academico").click()
    # 32 | select | id=id_nivel_academico | label=Bachiller
    dropdown = self.driver.find_element(By.ID, "id_nivel_academico")
    dropdown.find_element(By.XPATH, "//option[. = 'Bachiller']").click()
    # 33 | click | css=#id_nivel_academico > option:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, "#id_nivel_academico > option:nth-child(2)").click()
    # 34 | click | id=id_rol | 
    self.driver.find_element(By.ID, "id_rol").click()
    # 35 | select | id=id_rol | label=estudiante
    dropdown = self.driver.find_element(By.ID, "id_rol")
    dropdown.find_element(By.XPATH, "//option[. = 'estudiante']").click()
    # 36 | click | css=#id_rol > option:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, "#id_rol > option:nth-child(2)").click()
    # 37 | click | id=id_nacionalidad | 
    self.driver.find_element(By.ID, "id_nacionalidad").click()
    # 38 | select | id=id_nacionalidad | label=Guatemala, moneda: Quetzal
    dropdown = self.driver.find_element(By.ID, "id_nacionalidad")
    dropdown.find_element(By.XPATH, "//option[. = 'Guatemala, moneda: Quetzal']").click()
    # 39 | click | css=#id_nacionalidad > option:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, "#id_nacionalidad > option:nth-child(2)").click()
    # 40 | click | css=.btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
  
